# Generated by Django 5.2.15 on 2026-07-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=500)),
                ('title_az', models.CharField(max_length=500)),
                ('excerpt_en', models.TextField()),
                ('excerpt_az', models.TextField()),
                ('content_en', models.TextField()),
                ('content_az', models.TextField()),
                ('date_en', models.CharField(max_length=100)),
                ('date_az', models.CharField(max_length=100)),
                ('read_time', models.IntegerField(default=5)),
                ('source_url', models.URLField(max_length=1000)),
                ('icon', models.CharField(default='📰', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
