# Generated by Django 5.2.15 on 2026-07-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-id']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
